# Generated by Django 3.0.5 on 2020-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
