# Generated by Django 3.0.5 on 2020-04-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
