# Generated by Django 3.0.5 on 2020-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='user',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
