# Generated by Django 3.0.5 on 2020-04-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_itemorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='user',
        ),
    ]
