# Generated by Django 3.0.5 on 2020-04-06 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_itemorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_ordered', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
