# Generated by Django 3.0.5 on 2020-04-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
