# Generated by Django 3.0.5 on 2020-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200407_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='items',
            field=models.CharField(max_length=200),
        ),
    ]
