# Generated by Django 2.2.10 on 2020-04-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200408_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Items'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
