# Generated by Django 2.2.10 on 2020-04-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200409_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
