# Generated by Django 2.2.10 on 2020-04-09 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20200409_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederPlaced',
            new_name='OrderPlaced',
        ),
    ]
