# Generated by Django 2.2.10 on 2020-04-09 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200409_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 6, 54, 2, 44045, tzinfo=utc)),
        ),
    ]
